version: '3'
services:
 eslogs:
   image: elasticsearch:7.17.9
   container_name: eslogs
   volumes:
     - elasticsearch_data:/usr/share/elasticsearch/data
     - ./elastic/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
   ports:
     - 9200:9200
     - 9300:9300
   environment:
     discovery.type: single-node
     ELASTIC_PASSWORD: password
     node.name: eslogs

  # Kibana. Gotta have a pretty UI, amiright?
 kibana_demo:
   image: docker.elastic.co/kibana/kibana:7.17.9
   container_name: kibana_demo
   volumes:
   - ./elastic/kibana.yaml:/usr/share/kibana/config/kibana.yml
   ports:
     - 5601:5601
   environment:
     SERVER_PUBLICBASEURL: http://apps-dev.varcode.com:5601
     SERVER_NAME: apps-dev.varcode.com


  # All hail the mighty, mighty LOOOOOOOGSTAAAAAAAAASH:
 logstash_demo:
   image: logstash:7.17.9
   container_name: logstash_demo
   volumes:
   - ./elastic/logging.conf:/usr/share/logstash/pipeline/logging.conf
   - ./elastic/logstash.yaml:/usr/share/logstash/config/logstash.yml
   ports:
     - "5042:5042"
     - "50000:50000/tcp"
     - "50000:50000/udp"
     - "9600:9600"
   environment:
     LS_JAVA_OPTS: -Xms256m -Xmx256m

 apm-server:
    image: docker.elastic.co/apm/apm-server:7.17.9
    container_name: apm-server
    restart: unless-stopped
    command:
      - "--strict.perms=false"
    ports:
      - "8200:8200"
    volumes:
      - ./elastic/apm-config.yml:/usr/share/apm-server/apm-server.yml
    environment:
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: password

volumes:
  elasticsearch_data:
    driver: local
  api_db_data:
    driver: local
