version: '3'
services:
#  # NodeJS/ExpressJS server
# express_server:
#   container_name: expressjs
#   build:
#     context: ./
#     dockerfile: Dockerfile
#   volumes:
#   - './:/app'
#   - '/app/node_modules'
#   ports:
#     - 3000:3000
#     - 9229:9229
#   environment:
#     - NODE_ENV=dev
#   entrypoint: ["npm", "run", "dev"]

  # Elasticsearch
 eslogs:
   image: elasticsearch:7.17.9
   container_name: eslogs
   volumes:
     - elasticsearch_data:/usr/share/elasticsearch/data
     - ./elastic/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
   ports:
     - 9200:9200
     - 9300:9300
   environment:
     discovery.type: single-node
     KIBANA_SYSTEM_PASSWORD: password
     ELASTIC_PASSWORD: password
     node.name: eslogs
     LOGSTASH_INTERNAL_PASSWORD: password

  # Kibana. Gotta have a pretty UI, amiright?
 kibana_demo:
   image: docker.elastic.co/kibana/kibana:7.17.9
   container_name: kibana_demo
   volumes:
   - ./elastic/kibana.yaml:/usr/share/kibana/config/kibana.yml
   ports:
     - 5601:5601
   environment:
     ELASTIC_PASSWORD: password
     SERVER_NAME: apps-dev.varcode.com
     KIBANA_SYSTEM_PASSWORD: password
  # All hail the mighty, mighty LOOOOOOOGSTAAAAAAAAASH:
 logstash_demo:
   image: logstash:7.17.9
   container_name: logstash_demo
   volumes:
   - ./elastic/logging.conf:/usr/share/logstash/pipeline/logging.conf
   - ./elastic/logstash.yaml:/usr/share/logstash/config/logstash.yml
   ports:
   - 1514:1514/udp
   - 1515:1515
   - 1515:1515/udp
   environment:
     LS_JAVA_OPTS: -Xms256m -Xmx256m
     LOGSTASH_INTERNAL_PASSWORD: password
  # Postgres DB for saving stuff
#  db:
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: users
#    volumes:
#    - api_db_data:/var/lib/postgresql/data
#    ports:
#    - 5432:5432

volumes:
  elasticsearch_data:
    driver: local
  api_db_data:
    driver: local
